version: '3.7'
services:
  clash-server:
    image: dreamacro/clash
    container_name: clash
#    ports:
#      - "9090:9090"
#      - "7890:7890"
#      - "7891:7891"
    network_mode: host
    environment:
      - "TZ=Asia/Shanghai"
    volumes:
      - /data/clash/config.yaml:/root/.config/clash/config.yaml
    restart: unless-stopped

  clash-ui:
    image: haishanh/yacd
    container_name: clash-ui
    ports:
      - 7888:80
    environment:
      - "TZ=Asia/Shanghai"
    restart: unless-stopped
